apiVersion: v1
kind: Secret
metadata:
  name: slack-webhooks
  namespace: monitoring
type: Opaque
stringData:
  url: https://discord.com/api/webhooks/1486418475017834597/KAvynsz-FoNb8DznyQAa9EwwZSIYwqY5bubhDWbHIXwUY4zv2D4ZoUJtzv4aipFUFwpd