apiVersion: v1
kind: ConfigMap
metadata:
  name: devpulse-config
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "devpulse"
  DB_USER: "postgres"
  DB_SSLMODE: "disable"
  ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: devpulse-secrets
type: Opaque
data:
  # base64 encoded 'postgres'
  DB_PASSWORD: cG9zdGdyZXM=
  # base64 encoded placeholder
  JWT_SECRET: c2VjcmV0LWtleS1jaGFuZ2UtbWUtYmVmb3JlLWRlcGxveQ==
