apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devpulse-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devpulse-project
  source:
    repoURL: https://github.com/ShubhamShrestha60/Go-DevOps-Project.git
    targetRevision: main
    path: helm/charts/devpulse
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: devpulse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2